fix(helm): AE system mail notification without keystore
In the case of setting up SSL in `.notifiers.smtp.ssl` with `trustAll`
to `true` and without `keystore`. The helm chart set a null value for
`keyStore` and `keyStorePassword` in the `gravitee.yml` which make the
application exception on startup:

```
ERROR i.g.notifier.email.EmailNotifier - An error occurs while sending email
io.vertx.core.file.FileSystemException: Unable to read file at path ''
```

We make these fields optionable.

DV-329
APIM-3449